# Generated by Django 4.2.8 on 2024-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='file_path',
        ),
        migrations.AddField(
            model_name='recording',
            name='video_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
