# Generated by Django 4.2.13 on 2024-05-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="is_moderator",
            field=models.BooleanField(default=False),
        ),
    ]
