# Generated by Django 4.2.13 on 2024-05-31 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_visitor_is_moderator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitor",
            name="is_moderator",
        ),
    ]
